version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-replica
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_REPLICA_SET_NAME: rs0
    command: >
      mongod --replSet rs0 --bind_ip localhost,mongo
    volumes:
      - ./data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
